### ISSUE TITLE
Error:WSVR0605W: Thread "WorkManager.DefaultWorkManager : 0" (00000091) has been active for 690469 milliseconds and may be hung.  There is/are 1 thread(s) in total in the server that may be hung.

### ISSUE THREAD

**Issue by Ramnikov** [IBM/ansible-role-infosvr#31]
When installing Task **ansible-role-infosvr : engine - install engine tier silently**, the installation gets stuck with the following error:
```
[10/21/20 9:11:01:856 UTC] 00000140 ThreadMonitor W   WSVR0605W: Thread "WorkManager.DefaultWorkManager : 0" (00000091) has been active for 690469 milliseconds and may be hung.  There is/are 1 thread(s) in total in the server that may be hung.
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2050)
	at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:414)
	at com.ascential.investigate.utils.EventServiceUtils$EventConsumer.run(EventServiceUtils.java:65)
	at com.ibm.iis.isf.j2ee.impl.was.thread.WASScheduledExecutorService$RunnableWorkAdapter.run(WASScheduledExecutorService.java:875)
	at com.ibm.ws.asynchbeans.J2EEContext$RunProxy.run(J2EEContext.java:281)
	at java.security.AccessController.doPrivileged(AccessController.java:678)
	at com.ibm.ws.asynchbeans.J2EEContext.run(J2EEContext.java:747)
	at com.ibm.ws.asynchbeans.WorkWithExecutionContextImpl.go(WorkWithExecutionContextImpl.java:222)
	at com.ibm.ws.asynchbeans.ABWorkItemImpl.run(ABWorkItemImpl.java:206)
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1909)
```

If I install all on the same machine, it works correctly.

**Comment by Ramnikov** [comment]
After Analysing the issue we found that on Engine Server A script is missing:
/opt/IBM/InformationServer/ASBNode/bin/UpdateSignerCerts.sh

This script is prasent on Domain Server but not on Engine. Due to this the command of engine install is failing.

**Comment by Ramnikov** [comment]
The issue appears only on CentOS-7. Could not reproduce on RHEL-7
